name: SHEETS_PIPELINE

on: 
  push:
    branches: 
      - master

jobs: 
  build:
    steps:
      -name: Deployment
      run: |
        set -e
        npm run build
        cd dist
        git init
        git add -A
        git commit -m 'deploy'
        git push -f https://github.com/yaswankar/sheets-shelf.git master:gh-pages
        cd -